<?php

/**
 * @file
 * Contains sdss_profile_helper.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\menu_block\Plugin\Block\MenuBlock;

/**
 * Implements hook_block_view_BASE_BLOCK_ID_alter().
 */
function sdss_profile_helper_block_view_menu_block_alter(array &$build, MenuBlock $menu_block) {
  /** @var \Drupal\config_pages\ConfigPagesLoaderServiceInterface $config_pages */
  $config_pages = \Drupal::service('config_pages.loader');
  if ($menu_block->getPluginId() != 'menu_block:newsroom') {
    return;
  }
  $newsroom_menu_label = $config_pages->getValue('sdss_site_settings', 'su_newsroom_menu_label', 0, 'value');
  if ($newsroom_menu_label) {
    $menu_block->setConfigurationValue('label', t('@label', ['@label' => $newsroom_menu_label]));
  }
}

/**
 * Implements hook_form_views_exposed_form_alter().
 */
function sdss_profile_helper_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Optionally, restrict to specific views/displays using $form['#id'] or $form_state.
  $view = $form_state->getStorage()['view'];
  $row_plugin_id = $view->display_handler->getOption('row')['type'] ?? '';
  if ($row_plugin_id != 'grid_list_entity_row:entity:node_grid_list') {
    return;
  }
  $form['grid_list_display_mode'] = [
    '#type' => 'select',
    '#title' => t('Display mode'),
    '#options' => [
      'grid' => t('Grid'),
      'list' => t('List'),
    ],
    '#default_value' => 'grid',
    '#weight' => -10,
  ];
}
