_core:
  default_config_hash: eeL8a5_G3wIXAROFOujzvAGunSMyfnQVc6hPz3EHdfM
langcode: en
status: true
dependencies: {  }
id: stanford_earth_r25_credentialsettings
label: 'Stanford Earth R25 Credentials'
description: 'Credential settings for access to R25 API.'
stanford_r25_credential: /Users/ksharp/WWW/keys/r25cred
stanford_r25_base_url: 'https://webservices.collegenet.com/r25ws/wrd/stanford/run'
stanford_r25_room_image_directory: R25RoomPhotos
stanford_r25_credential_contact_id: '20727'
