<?php

/**
 * @file
 * Contains sdss_workgroup_tagging.module.
 */

use Drupal\sdss_workgroup_tagging\SdssWgTaggingUtil;

/**
 * Implements hook_cron().
 */
function sdss_workgroup_tagging_cron() {
  $tagger = new SdssWgTaggingUtil();
  $success = ' did not';
  if ($tagger->tagPersons()) {
    $success = '';
  }
  \Drupal::logger('sdss_workgroup_tagging')
    ->info('Workgroup tagging@success ran successfully.', ['@group' => $success]);
}
