<?php

/**
 * @file
 * Provides an sdss_entity entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\sdss_entities\Entity\SdssEntity;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function sdss_entities_theme() {
  return [
    'sdss_entity' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for SDSS entity templates.
 *
 * Default template: sdss-entity.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the sdss entity information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_sdss_entity(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
