<?php

/**
 * @file
 * Provides a sdss entity entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\sdss_entities\Entity\SdssEntity;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function sdss_entities_theme() {
  return [
    'sdss_entity' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for sdss entity templates.
 *
 * Default template: sdss-entity.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the sdss entity information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_sdss_entity(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function sdss_entities_user_cancel($edit, UserInterface $account, $method) {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish sdss entities.
      $storage = \Drupal::entityTypeManager()->getStorage('sdss_entity');
      $sdss_entity_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->execute();
      foreach ($storage->loadMultiple($sdss_entity_ids) as $sdss_entity) {
        $sdss_entity->set('status', FALSE);
        $sdss_entity->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize sdss entities.
      $storage = \Drupal::entityTypeManager()->getStorage('sdss_entity');
      $sdss_entity_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->execute();
      foreach ($storage->loadMultiple($sdss_entity_ids) as $sdss_entity) {
        $sdss_entity->setOwnerId(0);
        $sdss_entity->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function sdss_entities_user_predelete(UserInterface $account) {
  // Delete sdss entities.
  $storage = \Drupal::entityTypeManager()->getStorage('sdss_entity');
  $sdss_entity_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->execute();
  $sdss_entities = $storage->loadMultiple($sdss_entity_ids);
  $storage->delete($sdss_entities);
}
