cache:
  http:
    s_maxage: 2628000
    404_max_age: 15
    302_max_age: 15
    301_max_age: 15
    5xx_max_age: 15
    stale_while_revalidate: 0
    stale_if_error: 0
    vary: ''
    mustrevalidate: false
    nocache: false
    nostore: false
  surrogate:
    maxage: 0
    nostore: false
