# .github/workflows/pull_request_actions.yml
# Actions triggered on pull_request.
# - Runs the tests workflow and deploys an artifact when tests pass.
name: Pull request actions

on:
  pull_request:
    types: [opened, reopened, ready_for_review, converted_to_draft, synchronize]

jobs:
  # Run tests on current PR branch.
  tests:
    uses: ./.github/workflows/tests.yml
    # Allow secrets to be used in the called workflow.
    secrets: inherit
  # Deploy branch after tests pass by calling deploy workflow.
  deploy:
    uses: ./.github/workflows/deploy_branch.yml
    with:
      branch: ${{ github.head_ref }}
    # Allow secrets to be used in the called workflow.
    secrets: inherit
    # needs: [tests]