name: Test trigger auto deploy
on: [push]
jobs:
  test_trigger_auto_deploy:
    name: Test trigger auto deploy
    runs-on: ubuntu-latest
    container:
      image: pookmish/drupal8ci:latest
    steps:
      - name: Run Unit Tests
        run: |
          echo this fails right? so no auto deploy
  # call auto-deploy workflow after tests pass
  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: [test_trigger_auto_deploy]
